allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - methanol@0.0.33 || 0.0.34 || 0.1.0 || 0.1.1 || 0.1.3
  - refui@0.18.0 || 0.20.0 || 0.20.1 || 0.20.3
  - '@rsbuild/core@2.1.13'
  - '@rspack/binding-darwin-arm64@2.1.10'
  - '@rspack/binding-darwin-x64@2.1.10'
  - '@rspack/binding-linux-arm64-gnu@2.1.10'
  - '@rspack/binding-linux-arm64-musl@2.1.10'
  - '@rspack/binding-linux-ppc64-gnu@2.1.10'
  - '@rspack/binding-linux-riscv64-gnu@2.1.10'
  - '@rspack/binding-linux-riscv64-musl@2.1.10'
  - '@rspack/binding-linux-s390x-gnu@2.1.10'
  - '@rspack/binding-linux-x64-gnu@2.1.10'
  - '@rspack/binding-linux-x64-musl@2.1.10'
  - '@rspack/binding-wasm32-wasi@2.1.10'
  - '@rspack/binding-win32-arm64-msvc@2.1.10'
  - '@rspack/binding-win32-ia32-msvc@2.1.10'
  - '@rspack/binding-win32-x64-msvc@2.1.10'
  - '@rspack/binding@2.1.10'
  - '@rspack/core@2.1.10'
